#!/bin/bash

EXIT=0

composer validate || EXIT=1

echo './vendor/bin/phpcs --standard=psr2 ./src'
./vendor/bin/phpcs --standard=psr2 ./src || EXIT=1

echo './vendor/bin/phpcs --standard=psr2 ./tests'
./vendor/bin/phpcs --standard=psr2 ./tests || EXIT=1

echo './vendor/bin/phpmd src/ text codesize,controversial,design,naming,unusedcode'
./vendor/bin/phpmd src/ text codesize,controversial,design,naming,unusedcode || EXIT=1

echo './vendor/bin/phpmd tests/ text codesize,controversial,design,naming,unusedcode'
./vendor/bin/phpmd tests/ text codesize,controversial,design,naming,unusedcode || EXIT=1

echo './vendor/bin/php-cs-fixer --dry-run --verbose --diff fix src --fixers=unused_use'
./vendor/bin/php-cs-fixer --dry-run --verbose --diff fix src --fixers=unused_use || EXIT=1

echo './vendor/bin/php-cs-fixer --dry-run --verbose --diff fix tests --fixers=unused_use'
./vendor/bin/php-cs-fixer --dry-run --verbose --diff fix tests --fixers=unused_use || EXIT=1

echo './vendor/bin/phpunit'
./vendor/bin/phpunit || EXIT=1

exit $EXIT
